export const COUNTRIES = [
  {
    name: "Hrvatska",
    slug: "hrvatska",
    code: "HR",
    flag: "\ud83c\udded\ud83c\uddf7",
    regions: [
      {
        name: "Grad Zagreb",
        slug: "grad-zagreb",
        cities: [
          { name: "Zagreb", slug: "zagreb" },
          { name: "Sesvete", slug: "sesvete" },
          { name: "Dubrava", slug: "dubrava" },
          { name: "Novi Zagreb", slug: "novi-zagreb" },
        ],
      },
      {
        name: "Splitsko-dalmatinska",
        slug: "splitsko-dalmatinska",
        cities: [
          { name: "Split", slug: "split" },
          { name: "Makarska", slug: "makarska" },
          { name: "Solin", slug: "solin" },
          { name: "Kaštela", slug: "kastela" },
          { name: "Sinj", slug: "sinj" },
          { name: "Omiš", slug: "omis" },
          { name: "Trogir", slug: "trogir" },
          { name: "Imotski", slug: "imotski" },
          { name: "Supetar", slug: "supetar" },
          { name: "Hvar", slug: "hvar" },
          { name: "Vis", slug: "vis" },
        ],
      },
      {
        name: "Primorsko-goranska",
        slug: "primorsko-goranska",
        cities: [
          { name: "Rijeka", slug: "rijeka" },
          { name: "Opatija", slug: "opatija" },
          { name: "Crikvenica", slug: "crikvenica" },
          { name: "Krk", slug: "krk" },
          { name: "Mali Lošinj", slug: "mali-losinj" },
          { name: "Rab", slug: "rab" },
          { name: "Delnice", slug: "delnice" },
          { name: "Kastav", slug: "kastav" },
        ],
      },
      {
        name: "Osječko-baranjska",
        slug: "osjecko-baranjska",
        cities: [
          { name: "Osijek", slug: "osijek" },
          { name: "Đakovo", slug: "djakovo" },
          { name: "Valpovo", slug: "valpovo" },
          { name: "Beli Manastir", slug: "beli-manastir" },
          { name: "Belišće", slug: "belisce" },
          { name: "Našice", slug: "nasice" },
        ],
      },
      {
        name: "Istarska",
        slug: "istarska",
        cities: [
          { name: "Pula", slug: "pula" },
          { name: "Poreč", slug: "porec" },
          { name: "Rovinj", slug: "rovinj" },
          { name: "Pazin", slug: "pazin" },
          { name: "Labin", slug: "labin" },
          { name: "Umag", slug: "umag" },
          { name: "Novigrad", slug: "novigrad-istra" },
          { name: "Buzet", slug: "buzet" },
          { name: "Medulin", slug: "medulin" },
        ],
      },
      {
        name: "Zadarska",
        slug: "zadarska",
        cities: [
          { name: "Zadar", slug: "zadar" },
          { name: "Biograd na Moru", slug: "biograd-na-moru" },
          { name: "Benkovac", slug: "benkovac" },
          { name: "Nin", slug: "nin" },
          { name: "Pag", slug: "pag" },
          { name: "Obrovac", slug: "obrovac" },
        ],
      },
      {
        name: "Dubrovačko-neretvanska",
        slug: "dubrovacko-neretvanska",
        cities: [
          { name: "Dubrovnik", slug: "dubrovnik" },
          { name: "Metković", slug: "metkovic" },
          { name: "Ploče", slug: "ploce" },
          { name: "Korčula", slug: "korcula" },
          { name: "Cavtat", slug: "cavtat" },
          { name: "Opuzen", slug: "opuzen" },
        ],
      },
      {
        name: "Zagrebačka",
        slug: "zagrebacka",
        cities: [
          { name: "Velika Gorica", slug: "velika-gorica" },
          { name: "Samobor", slug: "samobor" },
          { name: "Zaprešić", slug: "zapresic" },
          { name: "Dugo Selo", slug: "dugo-selo" },
          { name: "Jastrebarsko", slug: "jastrebarsko" },
          { name: "Sveti Ivan Zelina", slug: "sveti-ivan-zelina" },
          { name: "Ivanić-Grad", slug: "ivanic-grad" },
          { name: "Vrbovec", slug: "vrbovec" },
        ],
      },
      {
        name: "Vukovarsko-srijemska",
        slug: "vukovarsko-srijemska",
        cities: [
          { name: "Vukovar", slug: "vukovar" },
          { name: "Vinkovci", slug: "vinkovci" },
          { name: "Županja", slug: "zupanja" },
          { name: "Ilok", slug: "ilok" },
        ],
      },
      {
        name: "Varaždinska",
        slug: "varazdinska",
        cities: [
          { name: "Varaždin", slug: "varazdin" },
          { name: "Ivanec", slug: "ivanec" },
          { name: "Ludbreg", slug: "ludbreg" },
          { name: "Novi Marof", slug: "novi-marof" },
          { name: "Lepoglava", slug: "lepoglava" },
        ],
      },
      {
        name: "Sisačko-moslavačka",
        slug: "sisacko-moslavacka",
        cities: [
          { name: "Sisak", slug: "sisak" },
          { name: "Kutina", slug: "kutina" },
          { name: "Novska", slug: "novska" },
          { name: "Petrinja", slug: "petrinja" },
          { name: "Glina", slug: "glina" },
          { name: "Hrvatska Kostajnica", slug: "hrvatska-kostajnica" },
        ],
      },
      {
        name: "Karlovačka",
        slug: "karlovacka",
        cities: [
          { name: "Karlovac", slug: "karlovac" },
          { name: "Ogulin", slug: "ogulin" },
          { name: "Duga Resa", slug: "duga-resa" },
          { name: "Slunj", slug: "slunj" },
          { name: "Ozalj", slug: "ozalj" },
        ],
      },
      {
        name: "Koprivničko-križevačka",
        slug: "koprivnicko-krizevacka",
        cities: [
          { name: "Koprivnica", slug: "koprivnica" },
          { name: "Križevci", slug: "krizevci" },
          { name: "Đurđevac", slug: "djurdjevac" },
        ],
      },
      {
        name: "Bjelovarsko-bilogorska",
        slug: "bjelovarsko-bilogorska",
        cities: [
          { name: "Bjelovar", slug: "bjelovar" },
          { name: "Daruvar", slug: "daruvar" },
          { name: "Čazma", slug: "cazma" },
          { name: "Garešnica", slug: "garesnica" },
          { name: "Grubišno Polje", slug: "grubisno-polje" },
        ],
      },
      {
        name: "Brodsko-posavska",
        slug: "brodsko-posavska",
        cities: [
          { name: "Slavonski Brod", slug: "slavonski-brod" },
          { name: "Nova Gradiška", slug: "nova-gradiska" },
        ],
      },
      {
        name: "Požeško-slavonska",
        slug: "pozesko-slavonska",
        cities: [
          { name: "Požega", slug: "pozega" },
          { name: "Pakrac", slug: "pakrac" },
          { name: "Pleternica", slug: "pleternica" },
          { name: "Lipik", slug: "lipik" },
        ],
      },
      {
        name: "Virovitičko-podravska",
        slug: "viroviticko-podravska",
        cities: [
          { name: "Virovitica", slug: "virovitica" },
          { name: "Slatina", slug: "slatina" },
          { name: "Orahovica", slug: "orahovica" },
        ],
      },
      {
        name: "Šibensko-kninska",
        slug: "sibensko-kninska",
        cities: [
          { name: "Šibenik", slug: "sibenik" },
          { name: "Knin", slug: "knin" },
          { name: "Drniš", slug: "drnis" },
          { name: "Vodice", slug: "vodice" },
        ],
      },
      {
        name: "Krapinsko-zagorska",
        slug: "krapinsko-zagorska",
        cities: [
          { name: "Krapina", slug: "krapina" },
          { name: "Zabok", slug: "zabok" },
          { name: "Pregrada", slug: "pregrada" },
          { name: "Zlatar", slug: "zlatar" },
          { name: "Klanjec", slug: "klanjec" },
        ],
      },
      {
        name: "Međimurska",
        slug: "medimurska",
        cities: [
          { name: "Čakovec", slug: "cakovec" },
          { name: "Prelog", slug: "prelog" },
          { name: "Mursko Središće", slug: "mursko-sredisce" },
        ],
      },
      {
        name: "Ličko-senjska",
        slug: "licko-senjska",
        cities: [
          { name: "Gospić", slug: "gospic" },
          { name: "Otočac", slug: "otocac" },
          { name: "Senj", slug: "senj" },
          { name: "Novalja", slug: "novalja" },
        ],
      },
    ],
  },
  {
    name: "Srbija",
    slug: "srbija",
    code: "RS",
    flag: "\ud83c\uddf7\ud83c\uddf8",
    regions: [
      {
        name: "Beograd",
        slug: "beograd-region",
        cities: [
          { name: "Beograd", slug: "beograd" },
          { name: "Novi Beograd", slug: "novi-beograd" },
          { name: "Zemun", slug: "zemun" },
          { name: "Rakovica", slug: "rakovica" },
          { name: "Voždovac", slug: "vozdovac" },
          { name: "Čukarica", slug: "cukarica" },
          { name: "Palilula", slug: "palilula" },
          { name: "Zvezdara", slug: "zvezdara" },
          { name: "Savski venac", slug: "savski-venac" },
          { name: "Stari grad", slug: "stari-grad-bg" },
          { name: "Vračar", slug: "vracar" },
          { name: "Surčin", slug: "surcin" },
        ],
      },
      {
        name: "Vojvodina",
        slug: "vojvodina",
        cities: [
          { name: "Novi Sad", slug: "novi-sad" },
          { name: "Subotica", slug: "subotica" },
          { name: "Zrenjanin", slug: "zrenjanin" },
          { name: "Pančevo", slug: "pancevo" },
          { name: "Sombor", slug: "sombor" },
          { name: "Kikinda", slug: "kikinda" },
          { name: "Sremska Mitrovica", slug: "sremska-mitrovica" },
          { name: "Vršac", slug: "vrsac" },
          { name: "Bečej", slug: "becej" },
          { name: "Inđija", slug: "indjija" },
          { name: "Ruma", slug: "ruma" },
          { name: "Šid", slug: "sid" },
          { name: "Stara Pazova", slug: "stara-pazova" },
          { name: "Bačka Palanka", slug: "backa-palanka" },
          { name: "Apatin", slug: "apatin" },
          { name: "Vrbas", slug: "vrbas" },
          { name: "Temerin", slug: "temerin" },
          { name: "Ada", slug: "ada" },
          { name: "Kanjiža", slug: "kanjiza" },
        ],
      },
      {
        name: "Šumadijski okrug",
        slug: "sumadijski-okrug",
        cities: [
          { name: "Kragujevac", slug: "kragujevac" },
          { name: "Aranđelovac", slug: "arandjelovac" },
          { name: "Topola", slug: "topola" },
        ],
      },
      {
        name: "Nišavski okrug",
        slug: "nisavski-okrug",
        cities: [
          { name: "Niš", slug: "nis" },
          { name: "Aleksinac", slug: "aleksinac" },
          { name: "Merošina", slug: "merosina" },
        ],
      },
      {
        name: "Moravički okrug",
        slug: "moravicki-okrug",
        cities: [
          { name: "Čačak", slug: "cacak" },
          { name: "Gornji Milanovac", slug: "gornji-milanovac" },
          { name: "Lučani", slug: "lucani" },
          { name: "Ivanjica", slug: "ivanjica" },
        ],
      },
      {
        name: "Zlatiborski okrug",
        slug: "zlatiborski-okrug",
        cities: [
          { name: "Užice", slug: "uzice" },
          { name: "Čajetina", slug: "cajetina" },
          { name: "Priboj", slug: "priboj" },
          { name: "Prijepolje", slug: "prijepolje" },
          { name: "Nova Varoš", slug: "nova-varos" },
          { name: "Bajina Bašta", slug: "bajina-basta" },
          { name: "Kosjerić", slug: "kosjeric" },
        ],
      },
      {
        name: "Raški okrug",
        slug: "raski-okrug",
        cities: [
          { name: "Kraljevo", slug: "kraljevo" },
          { name: "Novi Pazar", slug: "novi-pazar" },
          { name: "Vrnjačka Banja", slug: "vrnjacka-banja" },
          { name: "Raška", slug: "raska" },
          { name: "Tutin", slug: "tutin" },
        ],
      },
      {
        name: "Podunavski okrug",
        slug: "podunavski-okrug",
        cities: [
          { name: "Smederevo", slug: "smederevo" },
          { name: "Velika Plana", slug: "velika-plana" },
          { name: "Smederevska Palanka", slug: "smederevska-palanka" },
        ],
      },
      {
        name: "Pomoravski okrug",
        slug: "pomoravski-okrug",
        cities: [
          { name: "Jagodina", slug: "jagodina" },
          { name: "Paraćin", slug: "paracin" },
          { name: "Ćuprija", slug: "cuprija" },
          { name: "Svilajnac", slug: "svilajnac" },
          { name: "Despotovac", slug: "despotovac" },
        ],
      },
      {
        name: "Kolubarski okrug",
        slug: "kolubarski-okrug",
        cities: [
          { name: "Valjevo", slug: "valjevo" },
          { name: "Lajkovac", slug: "lajkovac" },
          { name: "Ljig", slug: "ljig" },
          { name: "Mionica", slug: "mionica" },
          { name: "Ub", slug: "ub" },
        ],
      },
      {
        name: "Mačvanski okrug",
        slug: "macvanski-okrug",
        cities: [
          { name: "Šabac", slug: "sabac" },
          { name: "Loznica", slug: "loznica" },
          { name: "Krupanj", slug: "krupanj" },
          { name: "Mali Zvornik", slug: "mali-zvornik" },
        ],
      },
      {
        name: "Pirotski okrug",
        slug: "pirotski-okrug",
        cities: [
          { name: "Pirot", slug: "pirot" },
          { name: "Babušnica", slug: "babusnica" },
          { name: "Bela Palanka", slug: "bela-palanka" },
          { name: "Dimitrovgrad", slug: "dimitrovgrad" },
        ],
      },
      {
        name: "Jablanički okrug",
        slug: "jablanicki-okrug",
        cities: [
          { name: "Leskovac", slug: "leskovac" },
          { name: "Vlasotince", slug: "vlasotince" },
          { name: "Lebane", slug: "lebane" },
        ],
      },
      {
        name: "Pčinjski okrug",
        slug: "pcinjski-okrug",
        cities: [
          { name: "Vranje", slug: "vranje" },
          { name: "Bujanovac", slug: "bujanovac" },
          { name: "Preševo", slug: "presevo" },
          { name: "Surdulica", slug: "surdulica" },
        ],
      },
      {
        name: "Borski okrug",
        slug: "borski-okrug",
        cities: [
          { name: "Bor", slug: "bor" },
          { name: "Zaječar", slug: "zajecar" },
          { name: "Negotin", slug: "negotin" },
          { name: "Kladovo", slug: "kladovo" },
          { name: "Majdanpek", slug: "majdanpek" },
        ],
      },
      {
        name: "Braničevski okrug",
        slug: "branicevski-okrug",
        cities: [
          { name: "Požarevac", slug: "pozarevac" },
          { name: "Veliko Gradište", slug: "veliko-gradiste" },
          { name: "Petrovac na Mlavi", slug: "petrovac-na-mlavi" },
          { name: "Kučevo", slug: "kucevo" },
        ],
      },
      {
        name: "Toplički okrug",
        slug: "toplicki-okrug",
        cities: [
          { name: "Prokuplje", slug: "prokuplje" },
          { name: "Kuršumlija", slug: "kursumlija" },
          { name: "Blace", slug: "blace" },
        ],
      },
      {
        name: "Rasinski okrug",
        slug: "rasinski-okrug",
        cities: [
          { name: "Kruševac", slug: "krusevac" },
          { name: "Trstenik", slug: "trstenik" },
          { name: "Aleksandrovac", slug: "aleksandrovac" },
          { name: "Varvarin", slug: "varvarin" },
          { name: "Brus", slug: "brus" },
          { name: "Ćićevac", slug: "cicevac" },
        ],
      },
    ],
  },
  {
    name: "Bosna i Hercegovina",
    slug: "bosna-i-hercegovina",
    code: "BA",
    flag: "\ud83c\udde7\ud83c\udde6",
    regions: [
      {
        name: "Kanton Sarajevo",
        slug: "kanton-sarajevo",
        cities: [
          { name: "Sarajevo", slug: "sarajevo" },
          { name: "Ilidža", slug: "ilidza" },
          { name: "Hadžići", slug: "hadzici" },
          { name: "Vogošća", slug: "vogosca" },
          { name: "Ilijaš", slug: "ilijas" },
          { name: "Novo Sarajevo", slug: "novo-sarajevo" },
        ],
      },
      {
        name: "Tuzlanski kanton",
        slug: "tuzlanski-kanton",
        cities: [
          { name: "Tuzla", slug: "tuzla" },
          { name: "Živinice", slug: "zivinice" },
          { name: "Lukavac", slug: "lukavac" },
          { name: "Gračanica", slug: "gracanica" },
          { name: "Gradačac", slug: "gradacac" },
          { name: "Srebrenik", slug: "srebrenik" },
          { name: "Banovići", slug: "banovici" },
          { name: "Kalesija", slug: "kalesija" },
        ],
      },
      {
        name: "Zeničko-dobojski kanton",
        slug: "zenicko-dobojski",
        cities: [
          { name: "Zenica", slug: "zenica" },
          { name: "Visoko", slug: "visoko" },
          { name: "Kakanj", slug: "kakanj" },
          { name: "Maglaj", slug: "maglaj" },
          { name: "Tešanj", slug: "tesanj" },
          { name: "Žepče", slug: "zepce" },
          { name: "Zavidovići", slug: "zavidovici" },
          { name: "Breza", slug: "breza" },
          { name: "Vareš", slug: "vares" },
          { name: "Olovo", slug: "olovo" },
        ],
      },
      {
        name: "Hercegovačko-neretvanski kanton",
        slug: "hercegovacko-neretvanski",
        cities: [
          { name: "Mostar", slug: "mostar" },
          { name: "Čapljina", slug: "capljina" },
          { name: "Stolac", slug: "stolac" },
          { name: "Čitluk", slug: "citluk" },
          { name: "Konjic", slug: "konjic" },
          { name: "Jablanica", slug: "jablanica" },
          { name: "Prozor-Rama", slug: "prozor-rama" },
          { name: "Neum", slug: "neum" },
        ],
      },
      {
        name: "Unsko-sanski kanton",
        slug: "unsko-sanski-kanton",
        cities: [
          { name: "Bihać", slug: "bihac" },
          { name: "Cazin", slug: "cazin" },
          { name: "Velika Kladuša", slug: "velika-kladusa" },
          { name: "Sanski Most", slug: "sanski-most" },
          { name: "Bosanska Krupa", slug: "bosanska-krupa" },
          { name: "Ključ", slug: "kljuc" },
          { name: "Bužim", slug: "buzim" },
        ],
      },
      {
        name: "Srednjobosanski kanton",
        slug: "srednjobosanski-kanton",
        cities: [
          { name: "Travnik", slug: "travnik" },
          { name: "Vitez", slug: "vitez" },
          { name: "Novi Travnik", slug: "novi-travnik" },
          { name: "Bugojno", slug: "bugojno" },
          { name: "Jajce", slug: "jajce" },
          { name: "Kiseljak", slug: "kiseljak" },
          { name: "Busovača", slug: "busovaca" },
          { name: "Gornji Vakuf-Uskoplje", slug: "gornji-vakuf" },
          { name: "Fojnica", slug: "fojnica" },
          { name: "Donji Vakuf", slug: "donji-vakuf" },
        ],
      },
      {
        name: "Bosansko-podrinjski kanton",
        slug: "bosansko-podrinjski",
        cities: [
          { name: "Goražde", slug: "gorazde" },
          { name: "Ustikolina", slug: "ustikolina" },
          { name: "Pale-Prača", slug: "pale-praca" },
        ],
      },
      {
        name: "Zapadnohercegovački kanton",
        slug: "zapadnohercegovacki-kanton",
        cities: [
          { name: "Široki Brijeg", slug: "siroki-brijeg" },
          { name: "Ljubuški", slug: "ljubuski" },
          { name: "Grude", slug: "grude" },
          { name: "Posušje", slug: "posusje" },
        ],
      },
      {
        name: "Hercegbosanski kanton",
        slug: "hercegbosanski-kanton",
        cities: [
          { name: "Livno", slug: "livno" },
          { name: "Tomislavgrad", slug: "tomislavgrad" },
          { name: "Kupres", slug: "kupres" },
          { name: "Glamoč", slug: "glamoc" },
          { name: "Drvar", slug: "drvar" },
          { name: "Bosansko Grahovo", slug: "bosansko-grahovo" },
        ],
      },
      {
        name: "Posavski kanton",
        slug: "posavski-kanton",
        cities: [
          { name: "Orašje", slug: "orasje" },
          { name: "Odžak", slug: "odzak" },
          { name: "Domaljevac-Šamac", slug: "domaljevac-samac" },
        ],
      },
      {
        name: "Republika Srpska - Banja Luka",
        slug: "rs-banja-luka",
        cities: [
          { name: "Banja Luka", slug: "banja-luka" },
          { name: "Laktaši", slug: "laktasi" },
          { name: "Gradiška", slug: "gradiska" },
          { name: "Prnjavor", slug: "prnjavor" },
          { name: "Kotor Varoš", slug: "kotor-varos" },
          { name: "Čelinac", slug: "celinac" },
          { name: "Mrkonjić Grad", slug: "mrkonjic-grad" },
          { name: "Prijedor", slug: "prijedor" },
          { name: "Kozarska Dubica", slug: "kozarska-dubica" },
          { name: "Novi Grad", slug: "novi-grad-rs" },
          { name: "Srbac", slug: "srbac" },
        ],
      },
      {
        name: "Republika Srpska - Doboj",
        slug: "rs-doboj",
        cities: [
          { name: "Doboj", slug: "doboj" },
          { name: "Teslić", slug: "teslic" },
          { name: "Modriča", slug: "modrica" },
          { name: "Derventa", slug: "derventa" },
          { name: "Brod", slug: "brod" },
          { name: "Šamac", slug: "samac" },
        ],
      },
      {
        name: "Republika Srpska - Bijeljina",
        slug: "rs-bijeljina",
        cities: [
          { name: "Bijeljina", slug: "bijeljina" },
          { name: "Zvornik", slug: "zvornik" },
          { name: "Ugljevik", slug: "ugljevik" },
          { name: "Lopare", slug: "lopare" },
          { name: "Bratunac", slug: "bratunac" },
          { name: "Srebrenica", slug: "srebrenica" },
          { name: "Milići", slug: "milici" },
        ],
      },
      {
        name: "Republika Srpska - Trebinje",
        slug: "rs-trebinje",
        cities: [
          { name: "Trebinje", slug: "trebinje" },
          { name: "Gacko", slug: "gacko" },
          { name: "Bileća", slug: "bileca" },
          { name: "Nevesinje", slug: "nevesinje" },
          { name: "Foča", slug: "foca" },
          { name: "Višegrad", slug: "visegrad" },
          { name: "Rudo", slug: "rudo" },
        ],
      },
      {
        name: "Republika Srpska - Istočno Sarajevo",
        slug: "rs-istocno-sarajevo",
        cities: [
          { name: "Istočno Sarajevo", slug: "istocno-sarajevo" },
          { name: "Pale", slug: "pale" },
          { name: "Sokolac", slug: "sokolac" },
          { name: "Han Pijesak", slug: "han-pijesak" },
          { name: "Rogatica", slug: "rogatica" },
        ],
      },
      {
        name: "Brčko distrikt",
        slug: "brcko-distrikt",
        cities: [{ name: "Brčko", slug: "brcko" }],
      },
    ],
  },
  {
    name: "Crna Gora",
    slug: "crna-gora",
    code: "ME",
    flag: "\ud83c\uddf2\ud83c\uddea",
    regions: [
      {
        name: "Podgorica",
        slug: "podgorica-region",
        cities: [
          { name: "Podgorica", slug: "podgorica" },
          { name: "Golubovci", slug: "golubovci" },
          { name: "Tuzi", slug: "tuzi" },
        ],
      },
      {
        name: "Primorje",
        slug: "primorje",
        cities: [
          { name: "Budva", slug: "budva" },
          { name: "Bar", slug: "bar" },
          { name: "Kotor", slug: "kotor" },
          { name: "Herceg Novi", slug: "herceg-novi" },
          { name: "Tivat", slug: "tivat" },
          { name: "Ulcinj", slug: "ulcinj" },
        ],
      },
      {
        name: "Sjever",
        slug: "sjever",
        cities: [
          { name: "Nikšić", slug: "niksic" },
          { name: "Bijelo Polje", slug: "bijelo-polje" },
          { name: "Berane", slug: "berane" },
          { name: "Pljevlja", slug: "pljevlja" },
          { name: "Rožaje", slug: "rozaje" },
          { name: "Cetinje", slug: "cetinje" },
          { name: "Danilovgrad", slug: "danilovgrad" },
          { name: "Kolašin", slug: "kolasin" },
          { name: "Mojkovac", slug: "mojkovac" },
          { name: "Plav", slug: "plav" },
          { name: "Žabljak", slug: "zabljak" },
          { name: "Šavnik", slug: "savnik" },
          { name: "Plužine", slug: "pluzine" },
          { name: "Andrijevica", slug: "andrijevica" },
          { name: "Gusinje", slug: "gusinje" },
          { name: "Petnjica", slug: "petnjica" },
        ],
      },
    ],
  },
  {
    name: "Sjeverna Makedonija",
    slug: "sjeverna-makedonija",
    code: "MK",
    flag: "\ud83c\uddf2\ud83c\uddf0",
    regions: [
      {
        name: "Skopski region",
        slug: "skopski-region",
        cities: [
          { name: "Skoplje", slug: "skoplje" },
          { name: "Čair", slug: "cair" },
          { name: "Kisela Voda", slug: "kisela-voda" },
          { name: "Gazi Baba", slug: "gazi-baba" },
          { name: "Aerodrom", slug: "aerodrom" },
          { name: "Karpoš", slug: "karpos" },
          { name: "Centar", slug: "centar-skoplje" },
          { name: "Butel", slug: "butel" },
          { name: "Šuto Orizari", slug: "suto-orizari" },
          { name: "Saraj", slug: "saraj" },
        ],
      },
      {
        name: "Jugozapadni",
        slug: "jugozapadni",
        cities: [
          { name: "Ohrid", slug: "ohrid" },
          { name: "Struga", slug: "struga" },
          { name: "Kičevo", slug: "kicevo" },
          { name: "Debar", slug: "debar" },
          { name: "Makedonski Brod", slug: "makedonski-brod" },
        ],
      },
      {
        name: "Pelagonski",
        slug: "pelagonski",
        cities: [
          { name: "Bitola", slug: "bitola" },
          { name: "Prilep", slug: "prilep" },
          { name: "Kruševo", slug: "krusevo" },
          { name: "Demir Hisar", slug: "demir-hisar" },
          { name: "Resen", slug: "resen" },
        ],
      },
      {
        name: "Vardarski",
        slug: "vardarski",
        cities: [
          { name: "Veles", slug: "veles" },
          { name: "Kavadarci", slug: "kavadarci" },
          { name: "Negotino", slug: "negotino-mk" },
          { name: "Gevgelija", slug: "gevgelija" },
          { name: "Sveti Nikole", slug: "sveti-nikole" },
        ],
      },
      {
        name: "Istočni",
        slug: "istocni",
        cities: [
          { name: "Štip", slug: "stip" },
          { name: "Kočani", slug: "kocani" },
          { name: "Strumica", slug: "strumica" },
          { name: "Radoviš", slug: "radovis" },
          { name: "Berovo", slug: "berovo" },
          { name: "Delčevo", slug: "delcevo" },
          { name: "Vinica", slug: "vinica" },
          { name: "Probištip", slug: "probistip" },
        ],
      },
      {
        name: "Pološki",
        slug: "poloski",
        cities: [
          { name: "Tetovo", slug: "tetovo" },
          { name: "Gostivar", slug: "gostivar" },
          { name: "Brvenica", slug: "brvenica" },
          { name: "Želino", slug: "zelino" },
          { name: "Tearce", slug: "tearce" },
          { name: "Bogovinje", slug: "bogovinje" },
          { name: "Jegunovce", slug: "jegunovce" },
          { name: "Vrapčište", slug: "vrapciste" },
          { name: "Mavrovo i Rostuše", slug: "mavrovo-i-rostuse" },
        ],
      },
      {
        name: "Severoistočni",
        slug: "severoistocni",
        cities: [
          { name: "Kumanovo", slug: "kumanovo" },
          { name: "Kratovo", slug: "kratovo" },
          { name: "Kriva Palanka", slug: "kriva-palanka" },
          { name: "Rankovce", slug: "rankovce" },
          { name: "Staro Nagoričane", slug: "staro-nagoricane" },
        ],
      },
    ],
  },
  {
    name: "Slovenija",
    slug: "slovenija",
    code: "SI",
    flag: "\ud83c\uddf8\ud83c\uddee",
    regions: [
      {
        name: "Osrednjeslovenska",
        slug: "osrednjeslovenska",
        cities: [
          { name: "Ljubljana", slug: "ljubljana" },
          { name: "Domžale", slug: "domzale" },
          { name: "Kamnik", slug: "kamnik" },
          { name: "Grosuplje", slug: "grosuplje" },
          { name: "Vrhnika", slug: "vrhnika" },
          { name: "Medvode", slug: "medvode" },
          { name: "Logatec", slug: "logatec" },
          { name: "Škofljica", slug: "skofljica" },
          { name: "Trzin", slug: "trzin" },
          { name: "Brezovica", slug: "brezovica" },
          { name: "Litija", slug: "litija" },
        ],
      },
      {
        name: "Podravska",
        slug: "podravska",
        cities: [
          { name: "Maribor", slug: "maribor" },
          { name: "Ptuj", slug: "ptuj" },
          { name: "Slovenska Bistrica", slug: "slovenska-bistrica" },
          { name: "Lenart", slug: "lenart" },
          { name: "Ormož", slug: "ormoz" },
          { name: "Ruše", slug: "ruse" },
          { name: "Hoče-Slivnica", slug: "hoce-slivnica" },
          { name: "Duplek", slug: "duplek" },
          { name: "Pesnica", slug: "pesnica" },
          { name: "Kidričevo", slug: "kidricevo" },
        ],
      },
      {
        name: "Savinjska",
        slug: "savinjska",
        cities: [
          { name: "Celje", slug: "celje" },
          { name: "Velenje", slug: "velenje" },
          { name: "Žalec", slug: "zalec" },
          { name: "Šentjur", slug: "sentjur" },
          { name: "Šmarje pri Jelšah", slug: "smarje-pri-jelsah" },
          { name: "Rogaška Slatina", slug: "rogaska-slatina" },
          { name: "Laško", slug: "lasko" },
          { name: "Štore", slug: "store" },
          { name: "Slovenske Konjice", slug: "slovenske-konjice" },
        ],
      },
      {
        name: "Gorenjska",
        slug: "gorenjska",
        cities: [
          { name: "Kranj", slug: "kranj" },
          { name: "Škofja Loka", slug: "skofja-loka" },
          { name: "Tržič", slug: "trzic" },
          { name: "Jesenice", slug: "jesenice" },
          { name: "Radovljica", slug: "radovljica" },
          { name: "Bled", slug: "bled" },
          { name: "Naklo", slug: "naklo" },
          { name: "Žirovnica", slug: "zirovnica" },
          { name: "Bohinj", slug: "bohinj" },
          { name: "Kranjska Gora", slug: "kranjska-gora" },
        ],
      },
      {
        name: "Obalno-kraška",
        slug: "obalno-kraska",
        cities: [
          { name: "Koper", slug: "koper" },
          { name: "Izola", slug: "izola" },
          { name: "Piran", slug: "piran" },
          { name: "Sežana", slug: "sezana" },
          { name: "Komen", slug: "komen" },
          { name: "Divača", slug: "divaca" },
          { name: "Hrpelje-Kozina", slug: "hrpelje-kozina" },
        ],
      },
      {
        name: "Goriška",
        slug: "goriska",
        cities: [
          { name: "Nova Gorica", slug: "nova-gorica" },
          { name: "Ajdovščina", slug: "ajdovscina" },
          { name: "Tolmin", slug: "tolmin" },
          { name: "Idrija", slug: "idrija" },
          { name: "Cerkno", slug: "cerkno" },
          { name: "Most na Soči", slug: "most-na-soci" },
        ],
      },
      {
        name: "Pomurska",
        slug: "pomurska",
        cities: [
          { name: "Murska Sobota", slug: "murska-sobota" },
          { name: "Ljutomer", slug: "ljutomer" },
          { name: "Gornja Radgona", slug: "gornja-radgona" },
          { name: "Lendava", slug: "lendava" },
          { name: "Beltinci", slug: "beltinci" },
        ],
      },
      {
        name: "Jugovzhodna Slovenija",
        slug: "jugovzhodna-slovenija",
        cities: [
          { name: "Novo mesto", slug: "novo-mesto" },
          { name: "Trebnje", slug: "trebnje" },
          { name: "Črnomelj", slug: "crnomelj" },
          { name: "Metlika", slug: "metlika" },
          { name: "Kočevje", slug: "kocevje" },
          { name: "Ribnica", slug: "ribnica" },
          { name: "Semič", slug: "semic" },
        ],
      },
      {
        name: "Koroška",
        slug: "koroska",
        cities: [
          { name: "Slovenj Gradec", slug: "slovenj-gradec" },
          { name: "Ravne na Koroškem", slug: "ravne-na-koroskem" },
          { name: "Dravograd", slug: "dravograd" },
          { name: "Mežica", slug: "mezica" },
          { name: "Prevalje", slug: "prevalje" },
          { name: "Radlje ob Dravi", slug: "radlje-ob-dravi" },
        ],
      },
      {
        name: "Posavska",
        slug: "posavska",
        cities: [
          { name: "Krško", slug: "krsko" },
          { name: "Brežice", slug: "brezice" },
          { name: "Sevnica", slug: "sevnica" },
          { name: "Kostanjevica na Krki", slug: "kostanjevica-na-krki" },
          { name: "Radeče", slug: "radece" },
        ],
      },
      {
        name: "Zasavska",
        slug: "zasavska",
        cities: [
          { name: "Trbovlje", slug: "trbovlje" },
          { name: "Zagorje ob Savi", slug: "zagorje-ob-savi" },
          { name: "Hrastnik", slug: "hrastnik" },
        ],
      },
      {
        name: "Primorsko-notranjska",
        slug: "primorsko-notranjska",
        cities: [
          { name: "Postojna", slug: "postojna" },
          { name: "Ilirska Bistrica", slug: "ilirska-bistrica" },
          { name: "Pivka", slug: "pivka" },
        ],
      },
    ],
  },
];

export const CATEGORIES = [
  { name: "Escort", slug: "escort", order: 1 },
  { name: "Trans sex", slug: "trans-sex", order: 2 },
  { name: "Oralno", slug: "oralno", order: 3 },
  { name: "Pušenje", slug: "pusenje", order: 4 },
  { name: "Jebanje", slug: "jebanje", order: 5 },
  { name: "Masaža", slug: "masaza", order: 6 },
  { name: "Upoznavanje", slug: "upoznavanje", order: 7 },
  { name: "Webcam", slug: "webcam", order: 8 },
  { name: "Telefon", slug: "telefon", order: 9 },
  { name: "Ostalo", slug: "ostalo", order: 10 },
];
